### PR TITLE
feat: add order to section

### LINKED ISSUE #170: feat: add order to section

### PR DESCRIPTION
**Pull request by marianzburlea**
this closes #170

### CODE REVIEW

**Review by BogdanNegura — APPROVED** [review]
👍

**Comment by pavelciupitu** [comment]
It's ok!

**Review by QuintyHH — APPROVED** [review]
:100:

**Review by pavelciupitu — COMMENTED** [review]
ok!

**Review by pavelciupitu — APPROVED** [review]

**Review by tandaraelena — APPROVED** [review]
Great job !

**Review by RadosavAntonio — COMMENTED** [review]
💯

**Review by psyhedeliq — COMMENTED** [review]
This drag and drop is really AWESOME!
🥇

**Pull request merged**
