### PR TITLE
feat: implement login / logout through GitHub

### LINKED ISSUE #89: feat: implement login / logout through GitHub

### PR DESCRIPTION
**Pull request by marianzburlea**
this fixes #89

### CODE REVIEW

**Review by QuintyHH — APPROVED** [review]
💯

**Comment by pavelciupitu** [comment]
it's OK !!

**Comment by marianzburlea** [comment]
> it's OK !!

THanks a lot!

**Review by pavelciupitu — APPROVED** [review]
OK !!

**Review by psyhedeliq — APPROVED** [review]
🥇

**Review by pavelciupitu — APPROVED** [review]
Ok..

**Review by tandaraelena — APPROVED** [review]
💯

**Review by pavelciupitu — APPROVED** [review]
Ok again!

**Pull request merged**
