### PR TITLE
feat: log in or out to dashboard

### LINKED ISSUE #137: feat: log in or out to dashboard
* [ ] If you log in and you're on the root path `/` thand redirect to `/dashboard`
* [ ] If you are logged in and you are on the `/dashboard` path and you log out, redirect to the home page  with the rout `/`

### PR DESCRIPTION
**Pull request by psyhedeliq**
this fixes #137

### CODE REVIEW

**Review by BogdanNegura — COMMENTED** [review]
💯

**Review by marianzburlea — APPROVED** [review]
:100 correct, congratz @psyhedeliq

**Review by BogdanNegura — APPROVED** [review]
💯

**Review by psyhedeliq — COMMENTED** [review]
🥇

**Comment by marianzburlea** [comment]
you can all delete the branch if you want to with:
```
git branch -D feat--log-in-or-out-to-dashboard-#137
```

**Pull request merged**
