### PR TITLE
feat: Bogdan is super eager to start with updating this component to …

### PR DESCRIPTION
**Pull request by marianzburlea**
…hide the dashboard button when the user is not logged in

### CODE REVIEW

**Review by psyhedeliq — APPROVED** [review]
💯

**Review by marianzburlea — COMMENTED** [review]
well done @BogdanNegura !!
I'll get this merged into `dev` as soon as possible!

**Review by psyhedeliq — APPROVED** [review]
Nice! 🥇

**Review by BogdanNegura — APPROVED** [review]
👍

**Pull request merged**
