### PR TITLE
feat: create a copy button for title and description

### LINKED ISSUE #357: feat: create a copy button for title and description
In the admin area, create a copy button for the title, as well as the description.

### PR DESCRIPTION
**Pull request by marianzburlea**
this closes #357

Co-authored-by: Filip Cornel-Cristian <filipcornelcristian@gmail.com>

### CODE REVIEW

**Review by psyhedeliq — APPROVED** [review]
🚀 Awesomeness! 💻

**Comment by RadosavAntonio** [comment]
:100

**Review by RadosavAntonio — APPROVED** [review]
:100

**Review by mihaelachetran — COMMENTED** [review]
💯

**Pull request merged**
