### PR TITLE
fix: add navigate from reach/router

### PR DESCRIPTION
**Pull request by psyhedeliq**

### CODE REVIEW

**Review by psyhedeliq — COMMENTED** [review]
💯

**Review by BogdanNegura — APPROVED** [review]
👍  Nice

**Review by marianzburlea — APPROVED** [review]
I don't know how it got lost, I assume it's a bad merge.
Let's either investigate or pay attention next time.

Good job @psyhedeliq 
:100:

**Review by BogdanNegura — APPROVED** [review]
💯

**Comment by marianzburlea** [comment]
```
git branch -D fix/top-menu-import
```

**Pull request merged**
