### PR TITLE
feat: implement a CSS corner ribbon on the home page

### LINKED ISSUE #176: feat: implement a CSS corner ribbon on the home page
implement a CSS corner ribbon on the home page to reflect the video access status.

this is part of feat: enhance lecture with publish date and member level #173

### PR DESCRIPTION
**Pull request by tandaraelena**
this fixes #176

### CODE REVIEW

**Review by psyhedeliq — APPROVED** [review]
Good job Elena! 💯

**Review by QuintyHH — APPROVED** [review]
:100:

**Review by marianzburlea — APPROVED** [review]
:100:

**Review by marianzburlea — APPROVED** [review]

**Review by valentin3199 — APPROVED** [review]

**Review by RadosavAntonio — APPROVED** [review]
:)

**Comment by RealTimeCom** [comment]
what?

**Pull request merged**
