### PR TITLE
Initial meaningful style for chat

### PR DESCRIPTION
**Pull request by marianzburlea**

### CODE REVIEW

**Review by QuintyHH — CHANGES_REQUESTED** [review]
Just a test Request:  change transition from 0.25 to 0.5s in chat.style.js

**Review by marianzburlea — COMMENTED** [review]
Nice !

**Comment by marianzburlea** [comment]
> Just a test Request: change transition from 0.25 to 0.5s in chat.style.js

NO

**Review by tandaraelena — APPROVED** [review]
Great job!

**Review by QuintyHH — APPROVED** [review]

**Pull request merged**
